### ISSUE TITLE
Incorrect Order for Arguments

### ISSUE THREAD

**Issue by aburk3** [learn-co-curriculum/redux-initial-dispatch#10]
Towards the end of the page there are two lines that say: 

> Action is defined because we passed { type: '@@INIT' } into dispatch. And the second argument, state, comes from the first line of our file. However, it's not defined.

`State` is always the first argument as far as I can tell, not the second. Not a big deal, just caused me to double-take and re-read things.

**Comment by maxwellbenton** [comment]
Hi @aburk3,

Thank you for spotting this and opening this issue. We have updated this lesson's Readme and corrected this paragraph based on your feedback.

Thank you for contributing to a Learn lesson!
