### ISSUE TITLE
Typo in one of the examples

### ISSUE THREAD

**Issue by YneBuhs** [learn-co-curriculum/redux-initial-dispatch#8]
In the code snippet: 
`    dispatch({ type: '@@INIT' })
        -> { counter: 0 }
    dispatch({type: 'INCREASE'})
        -> { counter: 1 }
`

Should counter be count?

**Comment by marielfrank** [comment]
Also, shouldn't `dispatch({type: 'INCREASE'})` be `dispatch({type: 'INCREASE_COUNT'})`?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
